### ISSUE TITLE
EPIC: Present unit tests scenarios

### ISSUE THREAD

**Issue by Br3nda** [ServiceInnovationLab/RapuTure#62]
As a person trying to understand how legislation as code works, i may grasp it better if presented with pre-formed scenarios such as those in the unit tests yml files, so let's present these on the Rapu Ture web page to help me understand

https://app.leanboard.io/board/ba742200-2f2d-4a57-b841-0da79520f1ac

**Comment by Br3nda** [comment]
example unit test in yaml from the rule set https://github.com/ServiceInnovationLab/openfisca-aotearoa/blob/master/openfisca_aotearoa/tests/social_security/accommodation_supplement.yaml

```yaml
- name: Accommodation Supplement for a resident
  period: 2018-06
  absolute_error_margin: 0
  input_variables:
    age: 30
    is_resident: true
    social_security__is_ordinarily_resident_in_new_zealand: true
    social_security__has_accomodation_costs: true
    eligible_for_social_housing: false
    accommodation_supplement__below_income_threshold: true
    accommodation_supplement__below_cash_threshold: true
  output_variables:
social_security__eligible_for_accommodation_supplement: true
```
